name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: dimerun-h9-ubuntu2204
    steps:
    - name: mount .cache as tmpfs
      run: sudo mount -t tmpfs -o size=200G bazelcache /home/runner/.cache
    - run: sudo loginctl enable-linger runner
    - uses: actions/checkout@v4
    - run: make
    - run: make -C podman_image build-en
